<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/moodle.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/menu.css" />
<link rel="stylesheet" type="text/css" media="print" href="<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/menuprint.css" />
<!--[if IE 6]><style type="text/css">@import "<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/IE60Fixes.css";</style><![endif]-->
<!--[if IE 5.5000]><style type="text/css">@import "<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/IE55Fixes.css";</style><![endif]-->

<script type="text/javascript" src="<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/sm/c_config.js"></script>
<script type="text/javascript" src="<?php echo $GLOBALS["wgStylePath"] ?>/moodledocs/moodle/sm/c_smartmenus.js"></script>
